spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    password: qwe123
    url: jdbc:postgresql://localhost:5432/cbhpm
    username: postgres
  jpa:
    show-sql: true
    
  mail:
    defaultEncoding: UTF-8
    host: smtp.gmail.com
    username: smtp.maisvida@gmail.com
    password: qwer!1234    
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG    